@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTA1ODQ2NTl9.BtRLNAlqxkKUBR0YCFtHK4dCRVJ5dqYdaHouuulszSo

### Products Index
GET http://localhost:3000/products
Authorization: Bearer {{jwt}}


### Producst Show
GET http://localhost:3000/products/3

### Products Create

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Switch",
  "price": 300,
  "image_url": "No Image",
  "description": "Handheld gaming console."
}

### Products Update

PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "price": 1000
}

### Product Destroy

DELETE http://localhost:3000/products

### Suppliers Index
GET http://localhost:3000/suppliers

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name4",
  "email": "test4@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Orders Index
GET http://localhost:3000/orders
Authorization: Bearer {{jwt}}

### Orders Create
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
Content-Type: application/json


{
  "product_id": 1,
  "quantity": 1

}

### Orders Show
GET http://localhost:3000/orders/1
Authorization: Bearer {{jwt}}


### Carted Products Create
POST http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}


{
  "user_id": 1,
  "product_id": 2,
  "quantity": 5,
  "status": "carted" ,
  "order_id": 1
}

### Carted Products Index
GET http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}